# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7f1db72e9beedb73e4d46f2264d2c2ba"
name = "magprod"
handle = "magprod"
application_url = "https://shaw-adsl-highly-nm.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://shaw-adsl-highly-nm.trycloudflare.com/auth/callback",
  "https://shaw-adsl-highly-nm.trycloudflare.com/auth/shopify/callback",
  "https://shaw-adsl-highly-nm.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
